name: Generate Global Manifest

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate global_manifest.json
        run: |
          node <<'EOF'
          const fs = require('fs');
          const path = require('path');

          function getDirInfo(dirPath) {
            const stats = fs.statSync(dirPath);
            if (!stats.isDirectory()) return null;

            const result = {
              type: 'folder',
              folders: 0,
              files: 0,
              hasIndexHTML: false,
              size: '0',
              contents: {}
            };

            const entries = fs.readdirSync(dirPath);
            for (const entry of entries) {
              const fullPath = path.join(dirPath, entry);
              const entryStats = fs.statSync(fullPath);
              const size = entryStats.size;

              if (entryStats.isDirectory()) {
                result.folders++;
                result.contents[entry] = getDirInfo(fullPath);
              } else {
                result.files++;
                result.hasIndexHTML ||= entry.toLowerCase() === 'index.html';
                result.contents[entry] = {
                  type: 'file, ' + path.extname(entry).slice(1).toUpperCase(),
                  size: (size / 1024).toFixed(2) + ' KB'
                };
              }
            }
            return result;
          }

          const manifest = {
            "jayxdcode.github.io": getDirInfo(".")
          };

          fs.mkdirSync('global', { recursive: true });
          fs.writeFileSync('global/global_manifest.json', JSON.stringify(manifest, null, 2));
          EOF

      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: global_manifest
          path: global/global_manifest.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add global/global_manifest.json
          git commit -m "Updated ${{ github.repository }}'s directory manifest."
          git push